import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Providers from "./components/shared/Providers";
import PromoElement from "./components/shared/PromoElement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#F3F3F3]">
      <body>
        <Providers>
          <PromoElement />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
